spring:
  application:
    name: catologo-backend
  datasource:
    # A porta do BD é 5432, e a senha é 'postgres'
    url: jdbc:postgresql://localhost:5432/backend_catalogo_bd
    username: postgres
    password: postgres # <-- Credenciais simples para o container funcionar
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true